const elgameZone = document.getElementById("gameZone"),
  elsecondGameZone = document.getElementById("secondGameZone"),
  elUser = document.getElementById("user"),
  elRobot = document.getElementById("robot"),
  elHands = document.querySelectorAll(".js-hand"),
  elrefreshGame = document.getElementById("refresh"),
  elgameZoneInner = document.getElementById("gameZoneInner"),
  elStatus = document.getElementById("status"),
  elRules = document.getElementById("rules"),
  elRulesModal = document.getElementById("rulesModal"),
  elmodeChanger = document.getElementById("ModeChanger"),
  elrulesImage = document.getElementById("rulesImage");

export {
  elgameZone,
  elsecondGameZone,
  elUser,
  elRobot,
  elHands,
  elrefreshGame,
  elStatus,
  elgameZoneInner,
  elmodeChanger,
  elRules,
  elRulesModal,
  elrulesImage,
};